
import React from 'react';
import { UserRole, Course, Startup } from './types';

export const THEME = {
  green: '#00885a',
  yellow: '#fcd116',
  red: '#da121a',
  slate: '#334155'
};

export const TRANSLATIONS: Record<string, any> = {
  en: {
    home: "Home",
    support: "Support",
    education: "Education",
    contribute: "Contribute",
    innovation: "Innovation",
    login: "Login",
    heroTitle: "Powering Ethiopia's AI Revolution",
    heroSub: "Advancing national prosperity through artificial intelligence.",
    startLearning: "Start Learning AI",
    getSupport: "Get Support",
    mission: "Our Mission",
    missionText: "The Ethiopian Artificial Intelligence Institute (EAII) was established to spearhead the nation's journey into the 4th Industrial Revolution.",
    supportTitle: "Digital Support & Access Portal",
    supportSub: "Access EAII services, book appointments, and submit institutional requests easily.",
    educationTitle: "Digital Literacy & AI Education",
    educationSub: "Unlock your potential with lessons tailored for every age group.",
    contributeTitle: "Community AI Contribution",
    contributeSub: "Help train Ethiopia's AI models by contributing local datasets.",
    innovationTitle: "AI Collaboration Hub",
    innovationSub: "The central ecosystem for Ethiopia's startups and talent.",
    voiceDesc: "Voice Description",
    voiceDescHint: "Describe the image or text in your own voice if you prefer speaking.",
    submit: "Submit Contribution",
    loginToTrack: "Login Required",
    loginPrompt: "Please login to record your contributions under your profile (e.g., Alem M.).",
    selam: "Selam",
    welcomeWorkspace: "Welcome to your workspace.",
    continueLearning: "Continue Learning",
    cert: "Certification",
    certDesc: "Complete all modules to receive your official EAII certificate.",
    leaderboard: "Leaderboard",
    upload: "Upload",
    label: "Label",
    points: "points",
    activeCourses: "Active Courses",
    certificates: "Certificates"
  },
  am: {
    home: "መነሻ",
    support: "ድጋፍ",
    education: "ትምህርት",
    contribute: "ተሳትፎ",
    innovation: "ፈጠራ",
    login: "ይግቡ",
    heroTitle: "የኢትዮጵያን የሰው ሰራሽ አስተውሎት አብዮት ማጎልበት",
    heroSub: "በሰው ሰራሽ አስተውሎት አማካኝነት የሀገርን ብልጽግና ማረጋገጥ።",
    startLearning: "መማር ይጀምሩ",
    getSupport: "ድጋፍ ያግኙ",
    mission: "ራዕያችን",
    missionText: "የኢትዮጵያ ሰው ሰራሽ አስተውሎት ኢንስቲትዩት (EAII) ሀገሪቱን ወደ 4ኛው የኢንዱስትሪ አብዮት ለማሸጋገር የተቋቋመ ነው።",
    supportTitle: "ዲጂታል ድጋፍ እና መግቢያ ፖርታል",
    supportSub: "የEAII አገልግሎቶችን ያግኙ፣ ቀጠሮዎችን ይያዙ እና ጥያቄዎችን በቀላሉ ያቅርቡ።",
    educationTitle: "ዲጂታል ማንበብና መጻፍ እና የሰው ሰራሽ አስተውሎት ትምህርት",
    educationSub: "ለእያንዳንዱ የዕድሜ ክልል በተዘጋጁ ትምህርቶች አቅምዎን ያሳድጉ።",
    contributeTitle: "የማህበረሰብ ተሳትፎ",
    contributeSub: "የሀገር በቀል መረጃዎችን በማቅረብ የኢትዮጵያን የAI ሞዴሎች ለማሰልጠን ይርዱ።",
    innovationTitle: "የፈጠራ ትብብር ማዕከል",
    innovationSub: "ለኢትዮጵያ ስታርትአፖች እና ተሰጥኦዎች ማዕከላዊ ስነ-ምህዳር።",
    voiceDesc: "የድምፅ መግለጫ",
    voiceDescHint: "ከጽሑፍ ይልቅ ድምፅን የሚመርጡ ከሆነ ምስሉን በድምፅዎ ይግለጹ።",
    submit: "ተሳትፎን ይላኩ",
    loginToTrack: "መግባት ያስፈልጋል",
    loginPrompt: "ተሳትፎዎን በመገለጫዎ (ለምሳሌ አለም ኤም.) ስር ለመመዝገብ እባክዎ ይግቡ።",
    selam: "ሰላም",
    welcomeWorkspace: "ወደ የስራ ቦታዎ እንኳን ደህና መጡ።",
    continueLearning: "ትምህርቱን ይቀጥሉ",
    cert: "የምስክር ወረቀት",
    certDesc: "የEAII የምስክር ወረቀት ለማግኘት ሁሉንም ክፍሎች ያጠናቅቁ።",
    leaderboard: "ደረጃ ሰንጠረዥ",
    upload: "መላክ",
    label: "መሰየም",
    points: "ነጥቦች",
    activeCourses: "ንቁ ትምህርቶች",
    certificates: "የምስክር ወረቀቶች"
  },
  om: {
    home: "Ka'umsa",
    support: "Deeggarsa",
    education: "Barnoota",
    contribute: "Gumaacha",
    innovation: "Mala-fayyadama",
    login: "Seenaa",
    heroTitle: "Inqilaaba AI Itoophiyaa Humneessu",
    heroSub: "Barnoota nam-tolchee fayyadamuun badhaadhina biyyaalessaa guddisuu.",
    startLearning: "Barachuu Jalqabaa",
    getSupport: "Deeggarsa Argadhaa",
    mission: "Ergaa Keenya",
    missionText: "Dhaabbanni Saayinsii Nam-tolchee Itoophiyaa (EAII) biyyattii gara inqilaaba induustrii 4ffaa qajeelchuuf hundeeffame.",
    supportTitle: "Portal Deeggarsaa fi Galmaa Diጂታላ",
    supportSub: "Tajaajiloota EAII argachuuf, beellama qabachuuf fi gaaffii keessan dhiyeessuuf.",
    educationTitle: "Barnoota AI fi Literacy Digital",
    educationSub: `Barnoota garee umurii hundaaf qophaa'een dandeettii keessan guddisaa.`,
    contributeTitle: "Gumaacha AI Hawaasaa",
    contributeSub: "Dataa naannoo dhiyeessuun moodeelota AI Itoophiyaa leenjisuuf gargaaraa.",
    innovationTitle: "Giddu-gala Walta'iinsa Kalaqaa",
    innovationSub: "Ekosisteemii giddu-galeessaa start-up Itoophiyaa fi dandeettii.",
    voiceDesc: "Ibsa Sagalee",
    voiceDescHint: "Yoo barreessuu caalaa dubbachuu filattan sagalee keessaniin ibsaa.",
    submit: "Gumaacha Ergaa",
    loginToTrack: "Seenuun Barbaachisaadha",
    loginPrompt: `Gumaacha keessan piroofaayila keessan jalatti galmeessuuf maaloo seenaa (fkn. Alem M.).`,
    selam: "Selam",
    welcomeWorkspace: "Gara iddoo hojii keessaniitti nagaan dhuftan.",
    continueLearning: "Barumsa Itti Fufaa",
    cert: "Waraqaa Ragaa",
    certDesc: "Waraqaa ragaa EAII argachuuf kutaalee hunda xumuraa.",
    leaderboard: "Sadarkaa",
    upload: "Fe'uu",
    label: "Moggaasuu",
    points: "qabxii",
    activeCourses: "Barnoota Jalqabame",
    certificates: "Waraqaa Ragaa"
  }
};

export const COURSES: Course[] = [
  { id: '1', title: 'Intro to AI for Kids', category: 'Kids', progress: 80, image: 'https://picsum.photos/seed/kids/400/250' },
  { id: '2', title: 'Python for Data Science', category: 'Youth', progress: 45, image: 'https://picsum.photos/seed/py/400/250' },
  { id: '3', title: 'Machine Learning Basics', category: 'Youth', progress: 10, image: 'https://picsum.photos/seed/ml/400/250' },
  { id: '4', title: 'Digital Literacy 101', category: 'General', progress: 100, image: 'https://picsum.photos/seed/dig/400/250' },
];

export const STARTUPS: Startup[] = [
  { id: 's1', title: 'AgriTech AI', founder: 'Temesgen B.', description: 'Using computer vision to detect crop diseases in Teff.', tags: ['Agriculture', 'Vision'] },
  { id: 's2', title: 'HealthSync', founder: 'Israel K.', description: 'AI-driven diagnostic tool for remote health clinics.', tags: ['Healthcare', 'NLP'] },
  { id: 's3', title: 'Afaan Voice', founder: 'Kidus S.', description: 'High-quality TTS for local languages.', tags: ['Speech', 'Afaan Oromo'] },
];

export const NAV_LINKS = [
  { name: 'Home', path: '#home', key: 'home' },
  { name: 'Support', path: '#support', key: 'support' },
  { name: 'Education', path: '#education', key: 'education' },
  { name: 'Contribute', path: '#contribute', key: 'contribute' },
  { name: 'Innovation', path: '#innovation', key: 'innovation' },
];
